[package]
name = "standard-error"
description = "simplifies returning meaningful errors for axum services"
authors = ["ashupednekar <ashupednekar49@gmail.com>"]
version = "0.1.10"
edition = "2021"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = ">=0.7.0, <0.8.0", default-features = false, features = ["json"] }
config = { version = "0.14.0", default-features = false }
diesel = { version = "2.2.4", default-features = false, features = ["extras"], optional = true}
env_logger = "0.11.5"
git2 = {version = "0.18.2", optional = true}
http = "1.1"
hyper = { version = "1.4.1", default-features = false }
lazy_static = "1.5.0"
log = "0.4.22"
r2d2_postgres = { version = "0.18.1", optional = true }
reqwest = { version = "0.12.7", optional = true }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
serde_yaml = "0.9.34"
sqlx = { version = "0.8.3", features = ["postgres"], optional = true }
thiserror = "1.0.63"
validator = { version = "0.18.1", optional = true }
askama = { version = "0.14.0", features = ["derive", "serde_json"] , optional=true}
async-nats = { version = "0.41.0", optional = true }

[dev-dependencies]
tokio = { version = "1.39.2", features = ["test-util", "macros", "rt"] }

[features]
diesel = ["dep:diesel", "dep:r2d2_postgres"]
git = ["dep:git2"]
reqwest = ["dep:reqwest"]
validator = ["dep:validator"]
sqlx = ["dep:sqlx"]
askama = ["dep:askama"]
nats = ["dep:async-nats"]
